# Generated by Django 5.0.3 on 2024-03-16 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_book_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={},
        ),
    ]
