# Generated by Django 5.0.3 on 2024-03-17 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_task_delete_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['id']},
        ),
    ]
